// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package inodes

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	storage "github.com/theduckcompany/duckcloud/internal/tools/storage"

	time "time"

	uuid "github.com/theduckcompany/duckcloud/internal/tools/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// CreateDir provides a mock function with given fields: ctx, parent, name
func (_m *MockService) CreateDir(ctx context.Context, parent *INode, name string) (*INode, error) {
	ret := _m.Called(ctx, parent, name)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *INode, string) (*INode, error)); ok {
		return rf(ctx, parent, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *INode, string) *INode); ok {
		r0 = rf(ctx, parent, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *INode, string) error); ok {
		r1 = rf(ctx, parent, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFile provides a mock function with given fields: ctx, cmd
func (_m *MockService) CreateFile(ctx context.Context, cmd *CreateFileCmd) (*INode, error) {
	ret := _m.Called(ctx, cmd)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateFileCmd) (*INode, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateFileCmd) *INode); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateFileCmd) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRootDir provides a mock function with given fields: ctx
func (_m *MockService) CreateRootDir(ctx context.Context) (*INode, error) {
	ret := _m.Called(ctx)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*INode, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *INode); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, cmd
func (_m *MockService) Get(ctx context.Context, cmd *PathCmd) (*INode, error) {
	ret := _m.Called(ctx, cmd)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *PathCmd) (*INode, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *PathCmd) *INode); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *PathCmd) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllDeleted provides a mock function with given fields: ctx, limit
func (_m *MockService) GetAllDeleted(ctx context.Context, limit int) ([]INode, error) {
	ret := _m.Called(ctx, limit)

	var r0 []INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]INode, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []INode); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, inodeID
func (_m *MockService) GetByID(ctx context.Context, inodeID uuid.UUID) (*INode, error) {
	ret := _m.Called(ctx, inodeID)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*INode, error)); ok {
		return rf(ctx, inodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *INode); ok {
		r0 = rf(ctx, inodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, inodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNameAndParent provides a mock function with given fields: ctx, name, parent
func (_m *MockService) GetByNameAndParent(ctx context.Context, name string, parent uuid.UUID) (*INode, error) {
	ret := _m.Called(ctx, name, parent)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*INode, error)); ok {
		return rf(ctx, name, parent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *INode); ok {
		r0 = rf(ctx, name, parent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, name, parent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSumChildsSize provides a mock function with given fields: ctx, parent
func (_m *MockService) GetSumChildsSize(ctx context.Context, parent uuid.UUID) (uint64, error) {
	ret := _m.Called(ctx, parent)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uint64, error)); ok {
		return rf(ctx, parent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uint64); ok {
		r0 = rf(ctx, parent)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, parent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDelete provides a mock function with given fields: ctx, inode
func (_m *MockService) HardDelete(ctx context.Context, inode *INode) error {
	ret := _m.Called(ctx, inode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *INode) error); ok {
		r0 = rf(ctx, inode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MkdirAll provides a mock function with given fields: ctx, cmd
func (_m *MockService) MkdirAll(ctx context.Context, cmd *PathCmd) (*INode, error) {
	ret := _m.Called(ctx, cmd)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *PathCmd) (*INode, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *PathCmd) *INode); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *PathCmd) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchMove provides a mock function with given fields: ctx, source, parent, newName, modeTime
func (_m *MockService) PatchMove(ctx context.Context, source *INode, parent *INode, newName string, modeTime time.Time) (*INode, error) {
	ret := _m.Called(ctx, source, parent, newName, modeTime)

	var r0 *INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *INode, *INode, string, time.Time) (*INode, error)); ok {
		return rf(ctx, source, parent, newName, modeTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *INode, *INode, string, time.Time) *INode); ok {
		r0 = rf(ctx, source, parent, newName, modeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *INode, *INode, string, time.Time) error); ok {
		r1 = rf(ctx, source, parent, newName, modeTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Readdir provides a mock function with given fields: ctx, inode, paginateCmd
func (_m *MockService) Readdir(ctx context.Context, inode *INode, paginateCmd *storage.PaginateCmd) ([]INode, error) {
	ret := _m.Called(ctx, inode, paginateCmd)

	var r0 []INode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *INode, *storage.PaginateCmd) ([]INode, error)); ok {
		return rf(ctx, inode, paginateCmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *INode, *storage.PaginateCmd) []INode); ok {
		r0 = rf(ctx, inode, paginateCmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]INode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *INode, *storage.PaginateCmd) error); ok {
		r1 = rf(ctx, inode, paginateCmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterModification provides a mock function with given fields: ctx, inode, newSize, modeTime
func (_m *MockService) RegisterModification(ctx context.Context, inode *INode, newSize uint64, modeTime time.Time) error {
	ret := _m.Called(ctx, inode, newSize, modeTime)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *INode, uint64, time.Time) error); ok {
		r0 = rf(ctx, inode, newSize, modeTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: ctx, inode
func (_m *MockService) Remove(ctx context.Context, inode *INode) error {
	ret := _m.Called(ctx, inode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *INode) error); ok {
		r0 = rf(ctx, inode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
