// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package cron

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCronRunner is an autogenerated mock type for the CronRunner type
type MockCronRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *MockCronRunner) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCronRunner creates a new instance of MockCronRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronRunner {
	mock := &MockCronRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
