// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package masterkey

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	secret "github.com/theduckcompany/duckcloud/internal/tools/secret"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GenerateMasterKey provides a mock function with given fields: ctx, password
func (_m *MockService) GenerateMasterKey(ctx context.Context, password *secret.Text) error {
	ret := _m.Called(ctx, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *secret.Text) error); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsMasterKeyLoaded provides a mock function with given fields:
func (_m *MockService) IsMasterKeyLoaded() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsMasterKeyRegistered provides a mock function with given fields: ctx
func (_m *MockService) IsMasterKeyRegistered(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadMasterKeyFromPassword provides a mock function with given fields: ctx, password
func (_m *MockService) LoadMasterKeyFromPassword(ctx context.Context, password *secret.Text) error {
	ret := _m.Called(ctx, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *secret.Text) error); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Open provides a mock function with given fields: key
func (_m *MockService) Open(key *secret.SealedKey) (*secret.Key, error) {
	ret := _m.Called(key)

	var r0 *secret.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(*secret.SealedKey) (*secret.Key, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(*secret.SealedKey) *secret.Key); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secret.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(*secret.SealedKey) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SealKey provides a mock function with given fields: key
func (_m *MockService) SealKey(key *secret.Key) (*secret.SealedKey, error) {
	ret := _m.Called(key)

	var r0 *secret.SealedKey
	var r1 error
	if rf, ok := ret.Get(0).(func(*secret.Key) (*secret.SealedKey, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(*secret.Key) *secret.SealedKey); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secret.SealedKey)
		}
	}

	if rf, ok := ret.Get(1).(func(*secret.Key) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
