// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package uploads

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, upload
func (_m *MockService) Delete(ctx context.Context, upload *Upload) error {
	ret := _m.Called(ctx, upload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Upload) error); ok {
		r0 = rf(ctx, upload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOldest provides a mock function with given fields: ctx
func (_m *MockService) GetOldest(ctx context.Context) (*Upload, error) {
	ret := _m.Called(ctx)

	var r0 *Upload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*Upload, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *Upload); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Upload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, cmd
func (_m *MockService) Register(ctx context.Context, cmd *RegisterUploadCmd) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *RegisterUploadCmd) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
