// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package uploads

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	storage "github.com/theduckcompany/duckcloud/internal/tools/storage"

	uuid "github.com/theduckcompany/duckcloud/internal/tools/uuid"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, uploadID
func (_m *MockStorage) Delete(ctx context.Context, uploadID uuid.UUID) error {
	ret := _m.Called(ctx, uploadID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, uploadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, cmd
func (_m *MockStorage) GetAll(ctx context.Context, cmd *storage.PaginateCmd) ([]Upload, error) {
	ret := _m.Called(ctx, cmd)

	var r0 []Upload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.PaginateCmd) ([]Upload, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storage.PaginateCmd) []Upload); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Upload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storage.PaginateCmd) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, upload
func (_m *MockStorage) Save(ctx context.Context, upload *Upload) error {
	ret := _m.Called(ctx, upload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Upload) error); ok {
		r0 = rf(ctx, upload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
