// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package files

import (
	context "context"

	afero "github.com/spf13/afero"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/theduckcompany/duckcloud/src/tools/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, inodeID
func (_m *MockService) Delete(ctx context.Context, inodeID uuid.UUID) error {
	ret := _m.Called(ctx, inodeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, inodeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Open provides a mock function with given fields: ctx, inodeID
func (_m *MockService) Open(ctx context.Context, inodeID uuid.UUID) (afero.File, error) {
	ret := _m.Called(ctx, inodeID)

	var r0 afero.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (afero.File, error)); ok {
		return rf(ctx, inodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) afero.File); ok {
		r0 = rf(ctx, inodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, inodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
