// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package davsessions

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	secret "github.com/theduckcompany/duckcloud/internal/tools/secret"

	sqlstorage "github.com/theduckcompany/duckcloud/internal/tools/sqlstorage"

	uuid "github.com/theduckcompany/duckcloud/internal/tools/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, username, password
func (_m *MockService) Authenticate(ctx context.Context, username string, password secret.Text) (*DavSession, error) {
	ret := _m.Called(ctx, username, password)

	var r0 *DavSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, secret.Text) (*DavSession, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, secret.Text) *DavSession); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DavSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, secret.Text) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, cmd
func (_m *MockService) Create(ctx context.Context, cmd *CreateCmd) (*DavSession, string, error) {
	ret := _m.Called(ctx, cmd)

	var r0 *DavSession
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateCmd) (*DavSession, string, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateCmd) *DavSession); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DavSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateCmd) string); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *CreateCmd) error); ok {
		r2 = rf(ctx, cmd)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: ctx, cmd
func (_m *MockService) Delete(ctx context.Context, cmd *DeleteCmd) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *DeleteCmd) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAll provides a mock function with given fields: ctx, userID
func (_m *MockService) DeleteAll(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllForUser provides a mock function with given fields: ctx, userID, paginateCmd
func (_m *MockService) GetAllForUser(ctx context.Context, userID uuid.UUID, paginateCmd *sqlstorage.PaginateCmd) ([]DavSession, error) {
	ret := _m.Called(ctx, userID, paginateCmd)

	var r0 []DavSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *sqlstorage.PaginateCmd) ([]DavSession, error)); ok {
		return rf(ctx, userID, paginateCmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *sqlstorage.PaginateCmd) []DavSession); ok {
		r0 = rf(ctx, userID, paginateCmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DavSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *sqlstorage.PaginateCmd) error); ok {
		r1 = rf(ctx, userID, paginateCmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
